config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  namespace :api, defaults: { format: :json } do
    namespace "v1" do
      get "/links", to: "links#index"
      post "/links", to: "links#create"
      patch "/links/:id", to: "links#update"
    end
  end
  
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :new_session
  get "/logout", to: "sessions#destroy", as: :sign_out

  get "/users/new", to: "users#new", as: :sign_up
  post "/users/new", to: "users#create", as: :users

  patch "/links/:id", to: "links#update"
  get "/links/:id", to: "links#show", as: :link
  get "/links", to: "links#index", as: :links_index

end

app/models/link.rb
class Link < ActiveRecord::Base
  default_scope { order('created_at ASC') }
  validates :address, :url => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  validates_uniqueness_of :email
  validates :password, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  attr_accessor :password, :confirmation

  include BCrypt

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
  
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApiController

  def create
    new_link = Link.create!(link_params)
    current_user.links << new_link
    respond_with new_link
  end

  def index
    links = current_user.links
    respond_with links
  end

  def update
    link = Link.find(params[:id])
    link.read = params[:link][:read]
    link.save
    respond_with link
  end

  private

  def link_params
    params.require(:link).permit(:title, :address, :read)
  end
  
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  respond_to :json
  helper_method :current_user  

  def current_user
    @current_user ||= User.find(session[:user]) if session[:user]    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user]) if session[:user]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    if current_user
      @link = Link.new
      @links = current_user.links
    else
      flash[:error] = "Please sign in to see your links."
      redirect_to root_path
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    @link.update(link_params)
    if @link.save
      flash[:success] = "Link updated!"
      redirect_to link_path(@link)
    else
      flash[:error] = @link.errors.full_messages.join(", ")
      redirect_to link_path(@link)
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new(password: nil)
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user
      session[:user] = @user.id
      redirect_to links_index_path
    end
  end

  def destroy
    session.clear
    flash[:success] = "You have signed out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(password: nil)
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user] = user.id
      redirect_to links_index_path
    else
      redirect_to sign_up_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :sign_in
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thoughtbox</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>    
  </head>
  <body>

    <div class="header">
      <ul>
	<li id="home-link"><a href="/">Home</a></li>
	<li id="links-link"><%= link_to "Links", links_index_path if current_user %></li>
	<li id="sign-out"><%= link_to "Sign Out", sign_out_path if current_user %></li>
      </ul>
    </div>
    
    <% flash.each do |type, message| %>
    <div class="flash" id="flash-<%= type %>">
      <%= message %>
    </div>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/links/index.html.erb
<div class="warning">
</div>

<h1>Links Index Page</h1>

<div class="link-control">
  <h4>Add New Link</h4>
  <form class='new-link-form' >
    <div>
      <label for="title">Title:</label>
      <input type="text" id="title" name="link_title" />
    </div>

    <div>
      <label for="address">Url:</label>
      <input type="text" id="address" name="address" placeholder="http://www.google.com"/>
    </div>

    <div class="button">
      <button type="button">Save link</button>
    </div>
  </form>


  <h4>Search Links</h4>
  <form class="search">
    <div>
      <label for="search"></label>
      <input type="text" id="search" name="link_search" placeholder="begin typing"/>
    </div>
  </form>



  <h4>Filter or Sort</h4>
  <div class="modify">
  <form>
    <input type="radio" name="read" value="true"> Read<br>
    <input type="radio" name="read" value="false"> Unread<br>
    <input type="radio" name="read" value="all" checked> All<br>  
  </form>

  <div id="alpha-button"><button type="button" id="alphabetize">Alphabetize</button></div>
  </div>
</div>


<section class="link-list">
</section>

app/views/links/show.html.erb
<h1>Link Show/Edit Page</h1>

<%= form_for @link, :html => {:class => 'link-info'} do |f| %>
    <%= f.label :title %>:
    <%= f.text_field(:title, placeholder: "#{@link.title}") %><br />

    <%= f.label :address %>:
    <%= f.text_field :address, placeholder: "#{@link.address}" %><br />

    <%= f.submit "Update Link"%>
<% end %>

app/views/users/new.html.erb
<h1>New User Page</h1>

<%= form_for @user, :html => {:class => 'new-user'} do |f| %>
    <%= f.label :email %>:
    <%= f.text_field :email %><br />

    <%= f.label :password %>:
    <%= f.password_field :password %><br />

    <%= f.label :password_confirmation %>:
    <%= f.password_field :password_confirmation %><br />

    <%= f.submit "Create Account"%>
<% end %>

app/views/welcome/sign_in.html.erb
<h1>Log In or Sign Up</h1>

<aside class="sign-up">
    <%= link_to "Sign Up", sign_up_path %>
</aside>

<aside class="login">
    <%= link_to "Log in", login_path %>
</aside>